# Generated by Django 5.2.8 on 2025-12-17 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_review_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='review_review',
        ),
    ]
