# Generated by Django 6.0.1 on 2026-01-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_alter_review_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
    ]
