# Generated by Django 6.0.1 on 2026-01-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_alter_review_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_type',
            field=models.CharField(default='client', max_length=20),
        ),
    ]
