# Generated by Django 5.0 on 2026-01-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_availability_profile_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
