# Generated by Django 6.0 on 2026-01-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="progress",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
