# Generated by Django 6.0 on 2026-01-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_contract_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="bid_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
