# Generated by Django 6.0 on 2026-01-03 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_initial"),
        ("contracts", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="project",
        ),
        migrations.AddField(
            model_name="message",
            name="contract",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="contracts.contract",
            ),
            preserve_default=False,
        ),
    ]
