# Generated by Django 6.0 on 2026-01-04 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='skills_requird',
            new_name='skills_required',
        ),
    ]
