# Generated by Django 6.0 on 2026-01-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_skills_requird_project_skills_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
