# Generated by Django 5.2.8 on 2026-01-10 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_availability_notification'),
        ('chat', '0004_alter_message_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.conversation'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('proposal_submitted', 'New Proposal Submitted'), ('proposal_accepted', 'Proposal Accepted'), ('proposal_rejected', 'Proposal Rejected'), ('new_message', 'New Message')], max_length=50),
        ),
    ]
