# Generated by Django 5.2.8 on 2025-12-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_portfolioitem_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioItem',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
