# Generated by Django 5.2.8 on 2025-12-17 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'managed': False},
        ),
    ]
