# Generated by Django 5.2.8 on 2025-12-17 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'managed': False},
        ),
    ]
