# Generated by Django 4.2.7 on 2025-12-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_project_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
