# Generated by Django 6.0 on 2026-01-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_completed',
            new_name='profile_completed',
        ),
    ]
