# Generated by Django 4.2.7 on 2025-12-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimated_duration',
            field=models.PositiveIntegerField(default=30, help_text='Estimated duration in days'),
            preserve_default=False,
        ),
    ]
