# Generated by Django 6.0 on 2026-01-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='proposal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
