# Generated by Django 4.2.7 on 2026-01-11 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_notifications'),
        ('accounts', '0002_alter_skill_options'),
    ]

    operations = [
    ]
