# Generated by Django 5.2.8 on 2026-01-03 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contract_options_contract_client_and_more'),
    ]

    operations = [
    ]
