# Generated by Django 5.2.8 on 2026-01-03 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20260103_1044'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='agreed_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='deliverables',
            field=models.TextField(help_text='Detailed description of deliverables'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_schedule',
            field=models.TextField(help_text='Payment schedule and terms'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
