# Generated by Django 5.2.8 on 2026-01-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contract_agreed_amount_alter_contract_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='progress',
            field=models.IntegerField(default=0, help_text='Progress percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='progress_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time progress was updated', null=True),
        ),
    ]
