# Generated by Django 6.0 on 2026-01-04 21:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_duration'),
        ('proposals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together={('project', 'freelancer')},
        ),
    ]
