# Generated by Django 6.0 on 2025-12-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='education',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='experience_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.CharField(blank=True, help_text='Example: 1 month, 2 weeks', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Comma separated skills', null=True),
        ),
    ]
