# Generated by Django 6.0 on 2025-12-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_education_project_experience_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('INR', 'Rupees'), ('USD', 'Dollars')], default='INR', max_length=3),
        ),
    ]
